import QueryProvider from '@/context/QueryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Playfair } from 'next/font/google'
import AuthProvider from '@/context/Auth'
import { Toaster } from 'react-hot-toast'

const playfair = Playfair({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <QueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </QueryProvider>
        <Toaster containerClassName="font-sfpro" />
      </body>
    </html>
  )
}
